export const SCRAPER_SOURCES = [
  {
    id: 'myjobmag-jobs',
    name: 'MyJobMag Nigeria',
    kind: 'listing',
    url: 'https://www.myjobmag.com/jobs',
    enabled: true,
    notes: 'Static public jobs page. Review source terms and keep request frequency low.',
  },
  {
    id: 'scholars4dev-scholarships',
    name: 'Scholars4Dev',
    kind: 'scholarship',
    url: 'https://www.scholars4dev.com/',
    enabled: true,
    notes: 'Static public scholarship index. Detail-page verification is still required.',
  },
  {
    id: 'jobberman-jobs',
    name: 'Jobberman',
    kind: 'listing',
    url: 'https://www.jobberman.com/jobs',
    enabled: false,
    notes: 'Disabled because the page currently redirects to a tracking endpoint; audit before enabling.',
  },
  {
    id: 'ngcareers-jobs',
    name: 'NGCareers',
    kind: 'listing',
    url: 'https://www.ngcareers.com/',
    enabled: false,
    notes: 'Currently redirects to Jobberman; keep disabled until a stable public source is confirmed.',
  },
  {
    id: 'opportunity-desk-scholarships',
    name: 'Opportunity Desk',
    kind: 'scholarship',
    url: 'https://opportunitydesk.org/',
    enabled: false,
    notes: 'Public site returned rate limiting during audit; add a source-specific adapter before enabling.',
  },
  {
    id: 'mastercard-foundation-scholars',
    name: 'Mastercard Foundation Scholars Program',
    kind: 'scholarship',
    url: 'https://mastercardfdn.org/en/what-we-do/our-programs/mastercard-foundation-scholars-program/where-to-apply/',
    enabled: false,
    notes: 'Official program information page; application opportunities are institution-specific and need detail extraction.',
  },
  {
    id: 'tony-elumelu-foundation',
    name: 'Tony Elumelu Foundation',
    kind: 'scholarship',
    url: 'https://www.tonyelumelufoundation.org/tef-entrepreneurship-programme/',
    enabled: false,
    notes: 'Official program page; verify current application window and application URL before enabling.',
  },
  {
    id: 'unilag-opportunities',
    name: 'University of Lagos',
    kind: 'scholarship',
    url: 'https://unilag.edu.ng/',
    enabled: false,
    notes: 'Institution home page only; identify a stable scholarships/notices feed before enabling.',
  },
  {
    id: 'ui-opportunities',
    name: 'University of Ibadan',
    kind: 'scholarship',
    url: 'https://ui.edu.ng/',
    enabled: false,
    notes: 'Institution home page only; identify a stable scholarships/notices feed before enabling.',
  },
  {
    id: 'covenant-opportunities',
    name: 'Covenant University',
    kind: 'scholarship',
    url: 'https://covenantuniversity.edu.ng/',
    enabled: false,
    notes: 'Institution home page only; identify a stable scholarships/notices feed before enabling.',
  },
  {
    id: 'dangote-careers',
    name: 'Dangote Group Careers',
    kind: 'listing',
    url: 'https://www.dangote.com/careers/',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
  {
    id: 'mtn-nigeria-careers',
    name: 'MTN Nigeria Careers',
    kind: 'listing',
    url: 'https://www.mtnonline.com/careers/',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
  {
    id: 'flutterwave-careers',
    name: 'Flutterwave Careers',
    kind: 'listing',
    url: 'https://www.flutterwave.com/careers',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
  {
    id: 'pwc-nigeria-careers',
    name: 'PwC Nigeria Careers',
    kind: 'listing',
    url: 'https://www.pwc.com/ng/en/careers.html',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
  {
    id: 'access-bank-careers',
    name: 'Access Bank Careers',
    kind: 'listing',
    url: 'https://www.accessbankplc.com/careers',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
  {
    id: 'gtbank-careers',
    name: 'GTBank Careers',
    kind: 'listing',
    url: 'https://www.gtbank.com/careers',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
  {
    id: 'zenith-bank-careers',
    name: 'Zenith Bank Careers',
    kind: 'listing',
    url: 'https://www.zenithbank.com/careers/',
    enabled: false,
    notes: 'Official careers page; needs a source-specific adapter and terms audit.',
  },
]
